export const FilmsActionTypes = {
  FETCH_FILMS_REQUEST: "FETCH_FILMS_REQUEST",
  FETCH_FILMS_SUCCESS: "FETCH_FILMS_SUCCESS",
  FETCH_FILMS_FAILURE: "FETCH_FILMS_FAILURE",

  FETCH_FILM_DETAILS_REQUEST: "FETCH_FILM_DETAILS_REQUEST",
  FETCH_FILM_DETAILS_SUCCESS: "FETCH_FILM_DETAILS_SUCCESS",
  FETCH_FILM_DETAILS_FAILURE: "FETCH_FILM_DETAILS_FAILURE"
};


export const StarShipsActionTypes = {
  FETCH_STARSHIP_REQUEST: "FETCH_STARSHIP_REQUEST",
  FETCH_STARSHIP_SUCCESS: "FETCH_STARSHIP_SUCCESS",
  FETCH_STARSHIP_FAILURE: "FETCH_STARSHIP_FAILURE",

  FETCH_STARSHIP_DETAILS_REQUEST: "FETCH_STARSHIP_DETAILS_REQUEST",
  FETCH_STARSHIP_DETAILS_SUCCESS: "FETCH_STARSHIP_DETAILS_SUCCESS",
  FETCH_STARSHIP_DETAILS_FAILURE: "FETCH_STARSHIP_DETAILS_FAILURE"
};

export const VehiclesActionTypes = {
  FETCH_VEHICLES_REQUEST: "FETCH_VEHICLES_REQUEST",
  FETCH_VEHICLES_SUCCESS: "FETCH_VEHICLES_SUCCESS",
  FETCH_VEHICLES_FAILURE: "FETCH_VEHICLES_FAILURE",

  FETCH_VEHICLES_DETAILS_REQUEST: "FETCH_VEHICLES_DETAILS_REQUEST",
  FETCH_VEHICLES_DETAILS_SUCCESS: "FETCH_VEHICLES_DETAILS_SUCCESS",
  FETCH_VEHICLES_DETAILS_FAILURE: "FETCH_VEHICLES_DETAILS_FAILURE"
};

